### ISSUE TITLE
Wont create target folder

### ISSUE THREAD

**Issue by pteichner** [jinnovations/attribution-maven-plugin#2]
When using the plugin outside of a maven lifecycle that creates the target folder the plugin fails

**Comment by jrivard** [comment]
Having same issue!

**Comment by dibog** [comment]
After checking the repository I saw that the fix was already merged in.
Unfortuantly there is no new release published to maven central. 
@jalbr74 : It would be great if you could release this version.

**Comment by jalbr74** [comment]
OK, I just pushed to the Maven Repo. You should be able to see it here:
https://repo.maven.apache.org/maven2/com/github/jinnovations/attribution-maven-plugin/0.9.6/attribution-maven-plugin-0.9.6.jar

Thanks for the heads up!

Marking as closed.
